### ISSUE TITLE
Packages Missing for Bullseye

### ISSUE THREAD

**Issue by hellfire51** [ntd/ansible-role-nut#8]
Is it intended to install the `nut-monitor` GUI [package](https://packages.debian.org/buster/amd64/nut-monitor)?

I don't think most of the functionality enabled by this role requires the GTK GUI. This package doesn't seem to be available on Debian bullseye, causing the role to fail. Could packages be made configurable or maybe the `nut-monitor` package should just be excluded.

**Comment by ntd** [comment]
It seems `nut-monitor` [has been removed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885358) because unmaintained. With the default role you can override which packages are installed though, e.g.:
```
- role: ntd.nut
  nut_packages:
    - nut-client
    - nut-server
  nut_services:
    - nut-driver
    - nut-server
  nut_ups:
    - name: ...
      driver: ...
      device: ...
```
Please, check if something similar works in your environment.

I'm glad to accept patches that add `nut_packages` to the documentation and/or remove `nut-monitor` on Sid/Bullseye (on old Debian it **must** stay for backward compatibility).
